spring:
  http:
    encoding:
      force: true
  profiles:
    active: dev
  application:
    name: mybatisplus
  #  boot:
  #    admin:
  #      url: http://127.0.0.1:9999
  #      client:
  #        prefer-ip: true

  #  redis:
  #    port: ${redisbase.port}
  #    password: ${redisbase.password}
  #    database: ${redisbase.databasename}
  #    timeout: 0
  #    jedis:
  #      pool:
  #        max-idle: -1
  #        max-wait: -1
  #        max-active: -1
  #        min-idle: 1

  datasource:
#    url: jdbc:mysql://${database.host}:${database.port}/${database.databasename}?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&allowMultiQueries=true
    url: jdbc:mysql://${database.host}:${database.port}/${database.databasename}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false&useSSL=false&allowMultiQueries=true
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: ${mysqlSize.size}
      max-active: ${mysqlSize.max}
      min-idle: ${mysqlSize.min}
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 30
      test-while-idle: true
      keep-alive: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      test-on-borrow: true
      test-on-return: false
      min-evictable-idle-time-millis: 3600000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 300000
      remove-abandoned: true #是否自动回收超时连接
      remove-abandoned-timeout: 180 #超时时间(以秒数为单位)
      filter:
        config:
          enabled: false

mybatis-plus:
  mapper-locations: classpath*:sqlmap/**/*Mapper.xml
  #typeAliasesPackages: com.netx.*.model.*
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: person.zxc.md.mybatisplus.config.CustomMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
server:
  port: 9797

